# Generated by Django 5.2.6 on 2025-11-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_birth_date_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Sobre Mim'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='pt-br', max_length=10, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_style',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estilo de Viagem'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='Moeda'),
        ),
    ]
