# Generated by Django 5.2.6 on 2025-11-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
