# Generated by Django 5.2.6 on 2025-12-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('RASCUNHO', 'Rascunho')], default='ATIVO', max_length=10),
        ),
    ]
