# Generated by Django 5.2.6 on 2025-11-27 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='participantes',
            field=models.ManyToManyField(related_name='viagens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viagem',
            name='titulo',
            field=models.CharField(default='2025-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('TRANSPORTE', 'Transporte'), ('HOSPEDAGEM', 'Hospedagem'), ('LAZER', 'Lazer'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_pagas', to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='planner.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='Rateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='planner.despesa')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('despesa', 'participante')},
            },
        ),
    ]
