# Generated by Django 5.2.6 on 2025-11-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_viagem_participantes_viagem_titulo_despesa_rateio'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('RASCUNHO', 'Rascunho')], default='CONFIRMADO', max_length=20),
        ),
    ]
