# Generated by Django 5.2.6 on 2025-12-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_sugestao_voto'),
        ('planner', '0002_tripinvite_tripmember'),
    ]

    operations = [
    ]
