# Generated by Django 5.2.6 on 2025-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0002_trip_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
