# Generated by Django 5.2.6 on 2025-12-01 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_merge_0002_sugestao_voto_0002_tripinvite_tripmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('RASCUNHO', 'Rascunho')], db_index=True, default='CONFIRMADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['viagem', 'status'], name='planner_des_viagem__c9ca6f_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['pagador'], name='planner_des_pagador_2c8496_idx'),
        ),
        migrations.AddIndex(
            model_name='rateio',
            index=models.Index(fields=['despesa', 'participante'], name='planner_rat_despesa_63ba06_idx'),
        ),
        migrations.AddIndex(
            model_name='viagem',
            index=models.Index(fields=['-id'], name='planner_via_id_81c7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='viagem',
            index=models.Index(fields=['data_inicio'], name='planner_via_data_in_80735e_idx'),
        ),
    ]
