# Generated by Django 5.2.6 on 2025-12-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0003_merge_0002_sugestao_voto_0002_tripinvite_tripmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="viagem",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="trip_covers/"),
        ),
    ]
