# Generated by Django 5.2.6 on 2025-12-01 04:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'suggestion')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option',
        ),
    ]
